/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLihatPesan.java
 *
 * Created on Aug 6, 2010, 6:54:00 PM
 */

package widget;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author dosen3
 */
public final class DlgPreviewImage extends javax.swing.JDialog {
    private String FilePath="";
    public String link="";
    private static String var="";
    private static final Properties prop = new Properties();

    /** Creates new form DlgLihatPesan */
    public DlgPreviewImage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(10,10);
        setSize(700, 900);
        
        try {
            link = URLPATHIMAGES();
        } catch (Exception e) {
            System.out.println("E : " + e);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new widget.Panel();
        jLabel5 = new javax.swing.JLabel();
        button1 = new widget.Button();
        jSeparator2 = new javax.swing.JSeparator();
        button2 = new widget.Button();
        internalFrame1 = new widget.InternalFrame();
        ImagePrev = new javax.swing.JLabel();
        panelJudul1 = new widget.PanelJudul();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel1.setName("panel1"); // NOI18N
        panel1.setPreferredSize(new java.awt.Dimension(440, 27));
        panel1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(180, 180, 180));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setName("jLabel5"); // NOI18N
        panel1.add(jLabel5, java.awt.BorderLayout.CENTER);

        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsimage/control_power.png"))); // NOI18N
        button1.setMnemonic('C');
        button1.setText("Close");
        button1.setToolTipText("Alt+C");
        button1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button1.setName("button1"); // NOI18N
        button1.setPreferredSize(new java.awt.Dimension(100, 27));
        button1.setRoundRect(false);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel1.add(button1, java.awt.BorderLayout.LINE_END);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator2.setName("jSeparator2"); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(1, 1));
        panel1.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        button2.setMnemonic('C');
        button2.setText("Save As");
        button2.setToolTipText("Alt+C");
        button2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button2.setName("button2"); // NOI18N
        button2.setPreferredSize(new java.awt.Dimension(100, 27));
        button2.setRoundRect(false);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel1.add(button2, java.awt.BorderLayout.LINE_START);

        getContentPane().add(panel1, java.awt.BorderLayout.PAGE_END);

        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        ImagePrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagePrev.setName("ImagePrev"); // NOI18N
        ImagePrev.setPreferredSize(new java.awt.Dimension(300, 400));
        internalFrame1.add(ImagePrev, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        panelJudul1.setBackground(new java.awt.Color(255, 255, 255));
        panelJudul1.setName("panelJudul1"); // NOI18N
        panelJudul1.setPreferredSize(new java.awt.Dimension(440, 40));
        panelJudul1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":: PREVIEW FOTO::        ");
        jLabel1.setIconTextGap(2);
        jLabel1.setName("jLabel1"); // NOI18N
        panelJudul1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/file-edit-32x32.png"))); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        panelJudul1.add(jLabel2, java.awt.BorderLayout.WEST);

        getContentPane().add(panelJudul1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        dispose();
}//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        saveAsFromServer(FilePath);
    }//GEN-LAST:event_button2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPreviewImage dialog = new DlgPreviewImage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagePrev;
    private widget.Button button1;
    private widget.Button button2;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private widget.Panel panel1;
    private widget.PanelJudul panelJudul1;
    // End of variables declaration//GEN-END:variables

    public void tampil(String LocFile) {
    try {
        FilePath = LocFile;
        // Membaca gambar dari file
        BufferedImage bufferedImage = ImageIO.read(new File(LocFile));

        // Mendapatkan ukuran asli gambar
        int imgWidth = bufferedImage.getWidth();
        int imgHeight = bufferedImage.getHeight();

        // Mendapatkan ukuran JLabel tempat gambar akan ditampilkan
        int labelWidth = ImagePrev.getWidth();
        int labelHeight = ImagePrev.getHeight();

        // Menyesuaikan ukuran gambar agar tetap proporsional
        double scaleX = (double) labelWidth / imgWidth;
        double scaleY = (double) labelHeight / imgHeight;
        double scale = Math.max(scaleX, scaleY); // Pilih skala yang lebih kecil agar tidak melebihi JLabel

        int newWidth = (int) (imgWidth * scale);
        int newHeight = (int) (imgHeight * scale);

        // Melakukan scaling pada gambar
        Image scaledImage = bufferedImage.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

        // Menampilkan gambar dalam JLabel
        ImagePrev.setIcon(new ImageIcon(scaledImage));
        ImagePrev.setText(""); // Hapus teks jika gambar muncul
    } catch (Exception e) {
            e.printStackTrace();
         JOptionPane.showMessageDialog(null, "Maaf, Foto masih kosong, Harap pilih foto terlebih dahulu...!!!!");
    }
}
    
public void saveAsFromServer(String serverFilePath) {
    if (serverFilePath == null || serverFilePath.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tidak ada file yang dipilih!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Menampilkan dialog Save As
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan File Sebagai");

    File serverFile = new File(serverFilePath);
    fileChooser.setSelectedFile(new File(serverFile.getName())); // Default nama file

    int userSelection = fileChooser.showSaveDialog(null);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File destinationFile = fileChooser.getSelectedFile();

        try {
            // Menyalin file dari server ke lokasi yang dipilih pengguna
            Files.copy(Paths.get(serverFilePath), Paths.get(destinationFile.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);
            JOptionPane.showMessageDialog(null, "File berhasil disimpan di: " + destinationFile.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

public String saveToServer(String localFilePath, String noRM, String namaBayi, String type, String tgl_permintaan) {
        String savedFilePath = "";
        String tahun, bulan, tanggal;

        if (localFilePath == null || localFilePath.isEmpty() || noRM == null || namaBayi == null) {
            JOptionPane.showMessageDialog(null, "File atau informasi tidak lengkap!", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        // Format tanggal (Tahun/Bulan/Tanggal)
        if (tgl_permintaan == null || tgl_permintaan.trim().isEmpty()) {
            // Gunakan tanggal saat ini
            LocalDate today = LocalDate.now();
            tahun = String.valueOf(today.getYear());
            bulan = String.format("%02d", today.getMonthValue());
            tanggal = String.format("%02d", today.getDayOfMonth());
        } else {
            try {
                // Format input "2025-02-07 11:43:06"
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                LocalDateTime dateTime = LocalDateTime.parse(tgl_permintaan, formatter);

                tahun = String.valueOf(dateTime.getYear());
                bulan = String.format("%02d", dateTime.getMonthValue());
                tanggal = String.format("%02d", dateTime.getDayOfMonth());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Format tanggal tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
                return null;
            }
        }

        // Path server dengan struktur folder
        String link = "\\\\192.168.106.98\\SysAdmin\\Test Foto Bayi\\";
        String serverPath = link + tahun + "\\" + bulan + "\\" + tanggal;
        
        // Pastikan folder tujuan ada
        File serverFolder = new File(serverPath);
        if (!serverFolder.exists()) {
            boolean success = serverFolder.mkdirs();
            if (!success) {
                System.out.println("Gagal membuat folder: " + serverPath);
                return null; // Berhenti jika folder tidak bisa dibuat
            }
        }

        // Nama file baru (NoRM-NamaBayi.jpg)
        String newFileName = "(" + type + ")" + "-" + noRM + "-" + namaBayi.replace(" ", "_") + ".jpg";
        File destinationFile = new File(serverFolder, newFileName);
        
        try {
            // Copy file ke server
            Files.copy(Paths.get(localFilePath), Paths.get(destinationFile.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);

            savedFilePath = destinationFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, "File berhasil disimpan di: " + savedFilePath);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return savedFilePath; // Kembalikan path file di server
    }

    public boolean deleteFromServer(String filePath) {
        if (filePath == null || filePath.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Path file tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        File file = new File(filePath);

        if (!file.exists()) {
            JOptionPane.showMessageDialog(null, "File tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (file.delete()) {
            JOptionPane.showMessageDialog(null, "File berhasil dihapus: " + filePath);
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Gagal menghapus file!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    
    public static String URLPATHIMAGES(){
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
            var = prop.getProperty("FOTOBAYIPATHNAS");
        } catch (Exception e) {
            var = "";
        }
        return var;
    }
}
