/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package modif;

import fungsi.akses;
import simrskhanza.*;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import inventory.DlgCariKonversi;
import inventory.DlgCariObat;
import inventory.DlgCariObat2;
import inventory.DlgCariObat3;
import inventory.riwayatobat;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import keuangan.Jurnal;

/**
 *
 * @author perpustakaan
 */
public class DlgBatalPiutangkaryawan extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps, ps2;
    private ResultSet rs, rs2;
    private boolean sukses = true;
    private String aktifkanbatch = "no";
    private riwayatobat Trackobat = new riwayatobat();
    private Jurnal jur = new Jurnal();

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public DlgBatalPiutangkaryawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            aktifkanbatch = koneksiDB.AKTIFKANBATCHOBAT();
        } catch (Exception e) {
            System.out.println("E : " + e);
            aktifkanbatch = "no";
        }

        this.setLocation(8,1);
        setSize(885,674);
        
        //TCatatan.setText(TCatatan); 
        TCatatan.setLineWrap(true);
        TCatatan.setWrapStyleWord(true);
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        jLabel3 = new widget.Label();
        TNik = new widget.TextBox();
        TNmKaryawan = new widget.TextBox();
        jLabel9 = new widget.Label();
        Scroll3 = new widget.ScrollPane();
        TCatatan = new widget.TextArea();
        TNoPiutang = new widget.TextBox();
        jLabel4 = new widget.Label();
        TKdPetugas = new widget.TextBox();
        TNmPetugas = new widget.TextBox();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Hapus Piutang ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(865, 105));
        FormInput.setLayout(null);

        jLabel3.setText("Karyawan :");
        jLabel3.setName("jLabel3"); // NOI18N
        FormInput.add(jLabel3);
        jLabel3.setBounds(0, 10, 65, 23);

        TNik.setEditable(false);
        TNik.setHighlighter(null);
        TNik.setName("TNik"); // NOI18N
        FormInput.add(TNik);
        TNik.setBounds(70, 10, 90, 23);

        TNmKaryawan.setEditable(false);
        TNmKaryawan.setHighlighter(null);
        TNmKaryawan.setName("TNmKaryawan"); // NOI18N
        TNmKaryawan.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(TNmKaryawan);
        TNmKaryawan.setBounds(320, 10, 360, 23);

        jLabel9.setText("Alasan :");
        jLabel9.setName("jLabel9"); // NOI18N
        FormInput.add(jLabel9);
        jLabel9.setBounds(0, 80, 60, 23);

        Scroll3.setName("Scroll3"); // NOI18N
        Scroll3.setOpaque(true);

        TCatatan.setColumns(20);
        TCatatan.setRows(5);
        TCatatan.setName("TCatatan"); // NOI18N
        Scroll3.setViewportView(TCatatan);

        FormInput.add(Scroll3);
        Scroll3.setBounds(70, 80, 620, 50);

        TNoPiutang.setEditable(false);
        TNoPiutang.setHighlighter(null);
        TNoPiutang.setName("TNoPiutang"); // NOI18N
        FormInput.add(TNoPiutang);
        TNoPiutang.setBounds(170, 10, 140, 23);

        jLabel4.setText("Petugas :");
        jLabel4.setName("jLabel4"); // NOI18N
        FormInput.add(jLabel4);
        jLabel4.setBounds(0, 40, 65, 23);

        TKdPetugas.setEditable(false);
        TKdPetugas.setHighlighter(null);
        TKdPetugas.setName("TKdPetugas"); // NOI18N
        FormInput.add(TKdPetugas);
        TKdPetugas.setBounds(70, 40, 90, 23);

        TNmPetugas.setEditable(false);
        TNmPetugas.setHighlighter(null);
        TNmPetugas.setName("TNmPetugas"); // NOI18N
        FormInput.add(TNmPetugas);
        TNmPetugas.setBounds(170, 40, 510, 23);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(100, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if (TNik.getText().trim().equals("") || TNmKaryawan.getText().trim().equals("")) {
            Valid.textKosong(TNik, "No.Rekam Medis");
        } else if (TNoPiutang.getText().trim().equals("")) {
            Valid.textKosong(TNoPiutang, "No Rawat");
        } else if (TCatatan.getText().trim().equals("")) {
            Valid.textKosong(TCatatan, "Alasan");
        } else if(TCatatan.getText().trim().length() < 5) {
             JOptionPane.showMessageDialog(null,"Maaf, Alasan harus diisi minimal 5 karakter");
             TCatatan.requestFocus();
        }else {
            if (Sequel.menyimpantf("piutang_batal", "?,?,?,NOW() ", "piutang_batal", 3, new String[]{
                TNoPiutang.getText(), TCatatan.getText(), TKdPetugas.getText()
            }) == true) {
                if (hapusBayarPiutang(TNoPiutang.getText())) {
                    try {
                        ps = koneksi.prepareStatement(
                                "select nota_piutang, kd_bangsal from piutang where nota_piutang=?");
                        try {
                            ps.setString(1, TNoPiutang.getText());
                            rs = ps.executeQuery();
                            if (rs.next()) {
                                Sequel.AutoComitFalse();
                                sukses = true;
                                ps2 = koneksi.prepareStatement(
                                        "select kode_brng,jumlah,no_batch,no_faktur from detailpiutang where nota_piutang=? ");
                                try {
                                    ps2.setString(1, rs.getString(1));
                                    rs2 = ps2.executeQuery();
                                    while (rs2.next()) {
                                        if (aktifkanbatch.equals("yes")) {
                                            Sequel.mengedit("data_batch", "no_batch=? and kode_brng=? and no_faktur=?", "sisa=sisa+?", 4, new String[]{
                                                rs2.getString("jumlah"), rs2.getString("no_batch"), rs2.getString("kode_brng"), rs2.getString("no_faktur")
                                            });
                                            Trackobat.catatRiwayat(rs2.getString("kode_brng"), rs2.getDouble("jumlah"), 0, "Piutang", akses.getkode(), rs.getString("kd_bangsal"), "Hapus", rs2.getString("no_batch"), rs2.getString("no_faktur"), rs.getString("nota_piutang"));
                                            Sequel.menyimpan("gudangbarang", "'" + rs2.getString("kode_brng") + "','" + rs.getString("kd_bangsal") + "','" + rs2.getString("jumlah") + "','" + rs2.getString("no_batch") + "','" + rs2.getString("no_faktur") + "'",
                                                    "stok=stok+'" + rs2.getString("jumlah") + "'", "kode_brng='" + rs2.getString("kode_brng") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and no_batch='" + rs2.getString("no_batch") + "' and no_faktur='" + rs2.getString("no_faktur") + "'");
                                        } else {
                                            Trackobat.catatRiwayat(rs2.getString("kode_brng"), rs2.getDouble("jumlah"), 0, "Piutang", akses.getkode(), rs.getString("kd_bangsal"), "Hapus", "", "", rs.getString("nota_piutang"));
                                            Sequel.menyimpan("gudangbarang", "'" + rs2.getString("kode_brng") + "','" + rs.getString("kd_bangsal") + "','" + rs2.getString("jumlah") + "','',''",
                                                    "stok=stok+'" + rs2.getString("jumlah") + "'", "kode_brng='" + rs2.getString("kode_brng") + "' and kd_bangsal='" + rs.getString("kd_bangsal") + "' and no_batch='' and no_faktur=''");
                                        }
                                    }
                                } catch (Exception e) {
                                    sukses = false;
                                    System.out.println("Notif : " + e);
                                } finally {
                                    if (rs2 != null) {
                                        rs2.close();
                                    }
                                    if (ps2 != null) {
                                        ps2.close();
                                    }
                                }

                                if (sukses == true) {
                                    Sequel.queryu("delete from tampjurnal");
                                    Sequel.menyimpan("tampjurnal", "'" + Sequel.cariIsi("select Piutang_Obat from set_akun") + "','PIUTANG PASIEN','0','" + Sequel.cariIsi("select sisapiutang from piutang where nota_piutang='" + rs.getString("nota_piutang") + "'") + "'", "Rekening");
                                    Sequel.menyimpan("tampjurnal", "'" + Sequel.cariIsi("select Kontra_Piutang_Obat from set_akun") + "','KAS DI TANGAN','" + Sequel.cariIsi("select sisapiutang  from piutang where nota_piutang='" + rs.getString("nota_piutang") + "'") + "','0'", "Rekening");
                                    sukses = jur.simpanJurnal(rs.getString("nota_piutang"), "U", "BATAL PIUTANG OBAT DI " + Sequel.cariIsi("select bangsal.nm_bangsal from bangsal where bangsal.kd_bangsal='" + rs.getString("kd_bangsal") + "'").toUpperCase() + ", OLEH " + akses.getkode());
                                }

                                if (sukses == true) {
                                    Sequel.queryu("delete from piutang where nota_piutang='" + TNoPiutang.getText() + "'");
                                    Sequel.Commit();
                                } else {
                                    sukses = false;
                                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat pemrosesan data, transaksi dibatalkan.\nPeriksa kembali data sebelum melanjutkan menyimpan..!!");
                                    Sequel.RollBack();
                                }

                                Sequel.AutoComitTrue();
                                if (sukses == true) {
                                    BtnKeluarActionPerformed(evt);
                                }
                            }
                        } catch (Exception e) {
                            System.out.println("Notif : " + e);
                        } finally {
                            if (rs != null) {
                                rs.close();
                            }
                            if (ps != null) {
                                ps.close();
                            }
                        }
                    } catch (Exception ex) {
                        System.out.println(ex);
                    }
                }
            }
            BtnKeluarActionPerformed(evt);
        }
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,TCatatan,BtnKeluar);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TCatatan.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgBatalPiutangkaryawan dialog = new DlgBatalPiutangkaryawan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.PanelBiasa FormInput;
    private widget.ScrollPane Scroll3;
    private widget.TextArea TCatatan;
    private widget.TextBox TKdPetugas;
    private widget.TextBox TNik;
    private widget.TextBox TNmKaryawan;
    private widget.TextBox TNmPetugas;
    private widget.TextBox TNoPiutang;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel9;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables
    

    private void isKaryawan() {
        Sequel.cariIsi("select pegawai.nama from pegawai where pegawai.nik=? ",TNmKaryawan,TNik.getText());
    }
    
    private void isPsien() {
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TNmKaryawan,TNik.getText());
    }

    public void setNoRm(String nik, String no_piutang) {
        jLabel3.setText("Karyawan :");
        TNik.setText(nik); 
        TNoPiutang.setText(no_piutang);
        TKdPetugas.setText(akses.getkode());
        TNmPetugas.setText(Sequel.cariIsi("select pegawai.nama from pegawai where pegawai.nik='" + TKdPetugas.getText() + "'"));
        isKaryawan();   
        Sequel.cariIsi("select reg_batal.alasan from reg_batal where reg_batal.no_rawat=?",TCatatan,TNoPiutang.getText());       
    }
    
    public void setNoRm2(String nik, String no_piutang) {
        jLabel3.setText("Pasien :");
        TNik.setText(nik); 
        TNoPiutang.setText(no_piutang);
        TKdPetugas.setText(akses.getkode());
        TNmPetugas.setText(Sequel.cariIsi("select pegawai.nama from pegawai where pegawai.nik='" + TKdPetugas.getText() + "'"));
        isPsien();   
        Sequel.cariIsi("select reg_batal.alasan from reg_batal where reg_batal.no_rawat=?",TCatatan,TNoPiutang.getText());       
    }
    
    public void isCek(){
        BtnSimpan.setEnabled(true);
    }
    
    private boolean hapusBayarPiutang(String no_piutang){
        try {
            ps = koneksi.prepareStatement(
                    "select bp.tgl_bayar, bp.no_rawat, bp.kd_rek, bp.kd_rek_kontra, bp.besar_cicilan from bayar_piutang bp where bp.no_rawat=?");
            try {
                ps.setString(1, no_piutang);
                rs = ps.executeQuery();
                if (rs.next()) {                    
                    String tgl_bayar = rs.getString("tgl_bayar"), no_rawat = rs.getString("no_rawat"), kd_rek = rs.getString("kd_rek"), kd_rek_kontra = rs.getString("kd_rek_kontra"), cicilan = rs.getString("besar_cicilan");
                    Sequel.AutoComitFalse();
                    sukses = true;

                    if (Sequel.queryu2tf("delete from bayar_piutang where tgl_bayar=? and no_rkm_medis=? and no_rawat=? and kd_rek=? and kd_rek_kontra=?", 5, new String[]{
                        tgl_bayar,
                        "000000",
                        no_rawat,
                        kd_rek,
                        kd_rek_kontra
                    }) == true) {
                        Sequel.mengedit("piutang_pasien", "no_rawat='" + no_rawat + "'", "status='Belum Lunas'");
                        Sequel.mengedit("detail_piutang_pasien", "no_rawat='" + no_rawat + "' and nama_bayar='" + Sequel.cariIsi("select nama_bayar from akun_piutang where kd_rek=?", kd_rek_kontra) + "'", "sisapiutang=sisapiutang+" + cicilan);
                        Sequel.queryu("delete from tampjurnal");
                        Sequel.menyimpan("tampjurnal", "'" + kd_rek_kontra + "','BAYAR PIUTANG','" + cicilan + "','0'", "Rekening");
                        Sequel.menyimpan("tampjurnal", "'" + kd_rek + "','Kontra Akun','0','" + cicilan + "'", "Rekening");
                        sukses = jur.simpanJurnal(no_rawat, "U", "PEMBATALAN BAYAR PIUTANG" + ", OLEH " + akses.getkode());
                    } else {
                        sukses = false;
                    }

                    if (sukses == true) {
                        Sequel.Commit();
                    } else {
                        sukses = false;
                        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat pemrosesan data, transaksi dibatalkan.\nPeriksa kembali data sebelum melanjutkan menyimpan..!!");
                        Sequel.RollBack();
                    }
                    Sequel.AutoComitTrue();
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            } finally {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }   
        if (sukses == false) {
            return false;
        }
        return true;
    }

}
