/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPemberianInfus.java
 *
 * Created on Jun 6, 2010, 10:59:33 PM
 */

package modif;

import simrskhanza.*;
import kepegawaian.DlgCariPetugas;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import kepegawaian.DlgCariDokter;
import keuangan.DlgKamar;
import laporan.DlgCariPenyakit;
import modif.DlgPendaftaranBayi;

/**
 *
 * @author dosen
 */
public class DlgGabungNota extends javax.swing.JDialog {
    private final DefaultTableModel tabModeGabungNota;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private Date date = new Date();
    private String now=dateFormat.format(date);
    private int i=0;
    private PreparedStatement ps;
    private ResultSet rsgabungnota;
    public  DlgCariPasien pasien=new DlgCariPasien(null,false);
    private PreparedStatement psgabungnota;
    private SimpleDateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");
    
    


    /** Creates new form DlgPemberianInfus
     * @param parent
     * @param modal */
    public DlgGabungNota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabModeGabungNota=new DefaultTableModel(null,new Object[]{"P","Nama Pasien", "No Rawat", "Tanggal Periksa", "Poli", "Dokter", "Total Billing"}){
              @Override 
              public boolean isCellEditable(int rowIndex, int colIndex){return true;}
             Class[] types = new Class[] {
                 java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, 
                 java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
             };
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }
        };
        tbGabungNota.setModel(tabModeGabungNota);

        tbGabungNota.setPreferredScrollableViewportSize(new Dimension(800,800));
        tbGabungNota.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 7; i++) {
            TableColumn column = tbGabungNota.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(20);
            }else if(i==1){
                column.setPreferredWidth(180);
            }else if(i==2){
                column.setPreferredWidth(120);
            }else if(i==3){
                column.setPreferredWidth(100);
            }else if(i==4){
                column.setPreferredWidth(180);
            }else if(i==5){
                column.setPreferredWidth(250);
            }else if(i==6){
                column.setPreferredWidth(120);
            }
        }
        tbGabungNota.setDefaultRenderer(Object.class, new WarnaTable());        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        stts_lanjut = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        scrollPane9 = new widget.ScrollPane();
        tbGabungNota = new widget.Table();
        panelisi3 = new widget.panelisi();
        label17 = new widget.Label();
        NoRM = new widget.TextBox();
        BtnCari1 = new widget.Button();
        R1 = new widget.RadioButton();
        R2 = new widget.RadioButton();
        R3 = new widget.RadioButton();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        BtnCetak = new widget.Button();
        BtnKeluar2 = new widget.Button();

        stts_lanjut.setEditable(false);
        stts_lanjut.setName("stts_lanjut"); // NOI18N
        stts_lanjut.setPreferredSize(new java.awt.Dimension(100, 23));
        stts_lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stts_lanjutActionPerformed(evt);
            }
        });
        stts_lanjut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stts_lanjutKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Cetak Gabung Nota ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        scrollPane9.setName("scrollPane9"); // NOI18N
        scrollPane9.setOpaque(true);

        tbGabungNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbGabungNota.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbGabungNota.setName("tbGabungNota"); // NOI18N
        scrollPane9.setViewportView(tbGabungNota);

        internalFrame1.add(scrollPane9, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label17.setText("No.RM :");
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label17);

        NoRM.setEditable(false);
        NoRM.setName("NoRM"); // NOI18N
        NoRM.setPreferredSize(new java.awt.Dimension(100, 23));
        NoRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoRMActionPerformed(evt);
            }
        });
        NoRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMKeyPressed(evt);
            }
        });
        panelisi3.add(NoRM);

        BtnCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari1.setMnemonic('2');
        BtnCari1.setToolTipText("Alt+2");
        BtnCari1.setName("BtnCari1"); // NOI18N
        BtnCari1.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCari1ActionPerformed(evt);
            }
        });
        panelisi3.add(BtnCari1);

        R1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(R1);
        R1.setSelected(true);
        R1.setText("10 Nota Terakhir");
        R1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R1.setName("R1"); // NOI18N
        R1.setPreferredSize(new java.awt.Dimension(120, 23));
        panelisi3.add(R1);

        R2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(R2);
        R2.setText(" Semua Nota");
        R2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R2.setName("R2"); // NOI18N
        R2.setPreferredSize(new java.awt.Dimension(104, 23));
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        panelisi3.add(R2);

        R3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(R3);
        R3.setText("Tanggal :");
        R3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R3.setName("R3"); // NOI18N
        R3.setPreferredSize(new java.awt.Dimension(75, 23));
        panelisi3.add(R3);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(90, 23));
        Tgl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tgl1KeyPressed(evt);
            }
        });
        panelisi3.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(25, 23));
        panelisi3.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(90, 23));
        Tgl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tgl2KeyPressed(evt);
            }
        });
        panelisi3.add(Tgl2);

        BtnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/print.png"))); // NOI18N
        BtnCetak.setMnemonic('S');
        BtnCetak.setText("Cetak Nota");
        BtnCetak.setToolTipText("Alt+S");
        BtnCetak.setName("BtnCetak"); // NOI18N
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });
        panelisi3.add(BtnCetak);

        BtnKeluar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar2.setMnemonic('U');
        BtnKeluar2.setText("Tutup");
        BtnKeluar2.setToolTipText("Alt+U");
        BtnKeluar2.setName("BtnKeluar2"); // NOI18N
        BtnKeluar2.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar2ActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar2);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void NoRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRMActionPerformed

    private void NoRMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoRMKeyPressed

    private void BtnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCari1ActionPerformed
        tampilGabungNota();
    }//GEN-LAST:event_BtnCari1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2ActionPerformed

    private void Tgl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tgl1KeyPressed
    
    }//GEN-LAST:event_Tgl1KeyPressed

    private void Tgl2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tgl2KeyPressed
        Valid.pindah(evt, Tgl1,NoRM);
    }//GEN-LAST:event_Tgl2KeyPressed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        try {
            Sequel.queryu2("delete from side_db.cetak_gabung_nota where ip='"+akses.getkode()+"'"); 
            for (i = 0; i < tbGabungNota.getRowCount(); i++) {
                if (tbGabungNota.getValueAt(i, 0).toString().equals("true")) {
                   Sequel.menyimpantf("side_db.cetak_gabung_nota", "?,?,?", "Nota Billing", 3, new String[]{
                        NoRM.getText(), tbGabungNota.getValueAt(i, 2).toString(), akses.getkode()
                    });
                }
            }
             Valid.panggilUrl("billing/LaporanBillingGabung.php?petugas="+akses.getkode().replaceAll(" ","_")+"&usere="+koneksiDB.USERHYBRIDWEB()+"&passwordte="+koneksiDB.PASHYBRIDWEB());
        } catch (Exception e) {
             System.out.println("Notifikasi : " + e);
        }
    }//GEN-LAST:event_BtnCetakActionPerformed

    private void BtnKeluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar2ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluar2ActionPerformed

    private void stts_lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stts_lanjutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stts_lanjutActionPerformed

    private void stts_lanjutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stts_lanjutKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stts_lanjutKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgGabungNota dialog = new DlgGabungNota(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari1;
    private widget.Button BtnCetak;
    private widget.Button BtnKeluar2;
    private widget.TextBox NoRM;
    private widget.RadioButton R1;
    private widget.RadioButton R2;
    private widget.RadioButton R3;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private javax.swing.ButtonGroup buttonGroup1;
    private widget.InternalFrame internalFrame1;
    private widget.Label label17;
    private widget.Label label18;
    private widget.panelisi panelisi3;
    private widget.ScrollPane scrollPane9;
    private widget.TextBox stts_lanjut;
    private widget.Table tbGabungNota;
    // End of variables declaration//GEN-END:variables

public void tampilGabungNota() {
       
        Valid.tabelKosong(tabModeGabungNota);
        try {
            if (R1.isSelected() == true) {
                psgabungnota = koneksi.prepareStatement("SELECT CONCAT(p.no_rkm_medis, ' ', p.nm_pasien) AS nama_pasien, rp.no_rawat, rp.tgl_registrasi, po.nm_poli,\n"
                        + "d.nm_dokter, sum(b.totalbiaya) AS total_biaya, rp.stts FROM reg_periksa rp \n"
                        + "left JOIN billing b ON b.no_rawat = rp.no_rawat\n"
                        + "INNER JOIN dokter d ON d.kd_dokter = rp.kd_dokter\n"
                        + "INNER JOIN pasien p ON p.no_rkm_medis = rp.no_rkm_medis\n"
                        + "INNER JOIN poliklinik po ON po.kd_poli = rp.kd_poli\n"
                        + "WHERE rp.no_rkm_medis = ? AND rp.status_lanjut = ? \n"
                        + "AND rp.stts != 'Batal'\n"
                        + "GROUP BY rp.no_rawat ORDER BY rp.tgl_registrasi DESC LIMIT 10");
            }else if(R2.isSelected()==true){
              psgabungnota = koneksi.prepareStatement("SELECT CONCAT(p.no_rkm_medis, ' ', p.nm_pasien) AS nama_pasien, rp.no_rawat, rp.tgl_registrasi, po.nm_poli,\n"
                        + "d.nm_dokter, sum(b.totalbiaya) AS total_biaya, rp.stts FROM reg_periksa rp \n"
                        + "left JOIN billing b ON b.no_rawat = rp.no_rawat\n"
                        + "INNER JOIN dokter d ON d.kd_dokter = rp.kd_dokter\n"
                        + "INNER JOIN pasien p ON p.no_rkm_medis = rp.no_rkm_medis\n"
                        + "INNER JOIN poliklinik po ON po.kd_poli = rp.kd_poli\n"
                        + "WHERE rp.no_rkm_medis = ? AND rp.status_lanjut = ? \n"
                        + "AND rp.stts != 'Batal'\n"
                        + "GROUP BY rp.no_rawat ORDER BY rp.tgl_registrasi DESC");
            }else if (R3.isSelected()==true){
                  psgabungnota = koneksi.prepareStatement("SELECT CONCAT(p.no_rkm_medis, ' ', p.nm_pasien) AS nama_pasien, rp.no_rawat, rp.tgl_registrasi, po.nm_poli,\n"
                        + "d.nm_dokter, sum(b.totalbiaya) AS total_biaya, rp.stts FROM reg_periksa rp \n"
                        + "left JOIN billing b ON b.no_rawat = rp.no_rawat\n"
                        + "INNER JOIN dokter d ON d.kd_dokter = rp.kd_dokter\n"
                        + "INNER JOIN pasien p ON p.no_rkm_medis = rp.no_rkm_medis\n"
                        + "INNER JOIN poliklinik po ON po.kd_poli = rp.kd_poli\n"
                        + "WHERE rp.no_rkm_medis = ? AND rp.status_lanjut = ? \n"
                        + "AND rp.stts != 'Batal' AND rp.tgl_registrasi between ? and ?\n"
                        + "GROUP BY rp.no_rawat ORDER BY rp.tgl_registrasi DESC");
            }

            try {
                 if(R1.isSelected()==true){
                    psgabungnota.setString(1,NoRM.getText().trim());
                    psgabungnota.setString(2,stts_lanjut.getText().trim());
                }else if(R2.isSelected()==true){
                    psgabungnota.setString(1,NoRM.getText().trim());
                    psgabungnota.setString(2,stts_lanjut.getText().trim());
                }else if(R3.isSelected()==true){
                    psgabungnota.setString(1,NoRM.getText().trim());
                    psgabungnota.setString(2,stts_lanjut.getText().trim());
                    psgabungnota.setString(3,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                    psgabungnota.setString(4,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                }
                rsgabungnota = psgabungnota.executeQuery();
                while (rsgabungnota.next()) {
                    tabModeGabungNota.addRow(new Object[]{false, rsgabungnota.getString("nama_pasien"), rsgabungnota.getString("no_rawat"), rsgabungnota.getString("tgl_registrasi"),
                        rsgabungnota.getString("nm_poli"), rsgabungnota.getString("nm_dokter"), rsgabungnota.getDouble("total_biaya")});
                }
            } catch (Exception e) {
                System.out.println("Notifikasi : " + e);
            } finally {
                if (rsgabungnota != null) {
                    rsgabungnota.close();
                }
                if (rsgabungnota != null) {
                    rsgabungnota.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
    }

    public void setNoRm(String no_rm, String stts) {
         NoRM.setText(no_rm);
         stts_lanjut.setText(stts);
    }
    
}
