/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLhtBiaya.java
 *
 * Created on 12 Jul 10, 16:21:34
 */

package modif;

import rekammedis.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.akses;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.methods.GetMethod;
import simrskhanza.DlgCariPasien;
import javax.swing.SwingWorker;


/**
 *
 * @author windiarto
 */
public final class RMRiwayatLaboratorium extends javax.swing.JDialog {    
    private validasi Valid=new validasi();    
    private final sekuel Sequel=new sekuel();
    private PreparedStatement ps,ps2;
    private ResultSet rs,rs2,rs3,rs4;
    private Connection koneksi=koneksiDB.condb();
    private int i=0,urut=0,w=0,s=0,urutdpjp=0, tinggi=0;
    private double biayaperawatan=0;
    private String kddpjp="",dpjp="",json,dokterrujukan="",polirujukan="",keputusan="",ke1="",ke2="",ke3="",ke4="",ke5="",ke6="",file="";
    private StringBuilder htmlContent;
    private HttpClient http = new HttpClient();
    private GetMethod get;
    private boolean esign=false,sertisign=false,ceksukses=false;
    private ObjectMapper mapper= new ObjectMapper();
    private JsonNode root;

    /** Creates new form DlgLhtBiaya
     * @param parent
     * @param modal */
    public RMRiwayatLaboratorium(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(8,1);
        setSize(885,674);
        
        NoRM.setDocument(new batasInput((byte)20).getKata(NoRM));
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTMLRiwayatPerawatan.setEditorKit(kit);
        
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}.isi a{text-decoration:none;color:#8b9b95;padding:0 0 0 0px;font-family: Tahoma;font-size: 8.5px;border: white;}");
        Document doc = kit.createDefaultDocument();
        LoadHTMLRiwayatPerawatan.setDocument(doc);
        LoadHTMLRiwayatPerawatan.setEditable(false);
        LoadHTMLRiwayatPerawatan.addHyperlinkListener(e -> {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(e.getEventType())) {
              Desktop desktop = Desktop.getDesktop();
              try {
                desktop.browse(e.getURL().toURI());
              } catch (Exception ex) {
                ex.printStackTrace();
              }
            }
        });


    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Pekerjaan = new widget.TextBox();
        Tanggal = new widget.Tanggal();
        internalFrame1 = new widget.InternalFrame();
        panelGlass5 = new widget.panelisi();
        R1 = new widget.RadioButton();
        R2 = new widget.RadioButton();
        R3 = new widget.RadioButton();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        BtnCari1 = new widget.Button();
        BtnKeluar = new widget.Button();
        PanelInput = new javax.swing.JPanel();
        ChkInput = new widget.CekBox();
        FormInput = new widget.panelisi();
        label17 = new widget.Label();
        NoRM = new widget.TextBox();
        NmPasien = new widget.TextBox();
        BtnPasien = new widget.Button();
        label20 = new widget.Label();
        Jk = new widget.TextBox();
        label21 = new widget.Label();
        TempatLahir = new widget.TextBox();
        label22 = new widget.Label();
        Alamat = new widget.TextBox();
        TanggalLahir = new widget.TextBox();
        panelGlass6 = new widget.panelisi();
        internalFrame2 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        LoadHTMLRiwayatPerawatan = new widget.editorpane();

        Pekerjaan.setEditable(false);
        Pekerjaan.setName("Pekerjaan"); // NOI18N
        Pekerjaan.setPreferredSize(new java.awt.Dimension(100, 23));

        Tanggal.setForeground(new java.awt.Color(50, 70, 50));
        Tanggal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "26-06-2026 10:14:03" }));
        Tanggal.setDisplayFormat("dd-MM-yyyy HH:mm:ss");
        Tanggal.setName("Tanggal"); // NOI18N
        Tanggal.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Data Riwayat/Pemeriksaan Laboratorium ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        R1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(R1);
        R1.setSelected(true);
        R1.setText("5 Riwayat Terakhir");
        R1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R1.setName("R1"); // NOI18N
        R1.setPreferredSize(new java.awt.Dimension(120, 23));
        panelGlass5.add(R1);

        R2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(R2);
        R2.setText("Semua Riwayat");
        R2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R2.setName("R2"); // NOI18N
        R2.setPreferredSize(new java.awt.Dimension(104, 23));
        panelGlass5.add(R2);

        R3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(R3);
        R3.setText("Tanggal :");
        R3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        R3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R3.setName("R3"); // NOI18N
        R3.setPreferredSize(new java.awt.Dimension(75, 23));
        panelGlass5.add(R3);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(90, 23));
        Tgl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tgl1KeyPressed(evt);
            }
        });
        panelGlass5.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(25, 23));
        panelGlass5.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(90, 23));
        Tgl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tgl2KeyPressed(evt);
            }
        });
        panelGlass5.add(Tgl2);

        BtnCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari1.setMnemonic('2');
        BtnCari1.setToolTipText("Alt+2");
        BtnCari1.setName("BtnCari1"); // NOI18N
        BtnCari1.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCari1ActionPerformed(evt);
            }
        });
        panelGlass5.add(BtnCari1);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        PanelInput.setBackground(new java.awt.Color(255, 255, 255));
        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setOpaque(false);
        PanelInput.setLayout(new java.awt.BorderLayout(1, 1));

        ChkInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setMnemonic('M');
        ChkInput.setSelected(true);
        ChkInput.setText(".: Tampilkan/Sembunyikan Data Pasien");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setFocusable(false);
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setPreferredSize(new java.awt.Dimension(192, 20));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        PanelInput.add(ChkInput, java.awt.BorderLayout.PAGE_END);

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(100, 40));
        FormInput.setLayout(null);

        label17.setText("Pasien :");
        label17.setName("label17"); // NOI18N
        label17.setPreferredSize(new java.awt.Dimension(55, 23));
        FormInput.add(label17);
        label17.setBounds(5, 10, 55, 23);

        NoRM.setName("NoRM"); // NOI18N
        NoRM.setPreferredSize(new java.awt.Dimension(100, 23));
        NoRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoRMKeyPressed(evt);
            }
        });
        FormInput.add(NoRM);
        NoRM.setBounds(64, 10, 100, 23);

        NmPasien.setEditable(false);
        NmPasien.setName("NmPasien"); // NOI18N
        NmPasien.setPreferredSize(new java.awt.Dimension(220, 23));
        FormInput.add(NmPasien);
        NmPasien.setBounds(167, 10, 220, 23);

        BtnPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/190.png"))); // NOI18N
        BtnPasien.setMnemonic('3');
        BtnPasien.setToolTipText("Alt+3");
        BtnPasien.setName("BtnPasien"); // NOI18N
        BtnPasien.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPasienActionPerformed(evt);
            }
        });
        BtnPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPasienKeyPressed(evt);
            }
        });
        FormInput.add(BtnPasien);
        BtnPasien.setBounds(390, 10, 28, 23);

        label20.setText("J.K. :");
        label20.setName("label20"); // NOI18N
        label20.setPreferredSize(new java.awt.Dimension(55, 23));
        FormInput.add(label20);
        label20.setBounds(436, 10, 30, 23);

        Jk.setEditable(false);
        Jk.setName("Jk"); // NOI18N
        Jk.setPreferredSize(new java.awt.Dimension(100, 23));
        FormInput.add(Jk);
        Jk.setBounds(470, 10, 40, 23);

        label21.setText("Tempat & Tgl.Lahir :");
        label21.setName("label21"); // NOI18N
        label21.setPreferredSize(new java.awt.Dimension(55, 23));
        FormInput.add(label21);
        label21.setBounds(523, 10, 110, 23);

        TempatLahir.setEditable(false);
        TempatLahir.setName("TempatLahir"); // NOI18N
        TempatLahir.setPreferredSize(new java.awt.Dimension(100, 23));
        FormInput.add(TempatLahir);
        TempatLahir.setBounds(637, 10, 140, 23);

        label22.setText("Alamat :");
        label22.setName("label22"); // NOI18N
        label22.setPreferredSize(new java.awt.Dimension(55, 23));
        FormInput.add(label22);
        label22.setBounds(870, 10, 55, 23);

        Alamat.setEditable(false);
        Alamat.setName("Alamat"); // NOI18N
        Alamat.setPreferredSize(new java.awt.Dimension(100, 23));
        FormInput.add(Alamat);
        Alamat.setBounds(930, 10, 300, 23);

        TanggalLahir.setEditable(false);
        TanggalLahir.setName("TanggalLahir"); // NOI18N
        TanggalLahir.setPreferredSize(new java.awt.Dimension(100, 23));
        FormInput.add(TanggalLahir);
        TanggalLahir.setBounds(779, 10, 83, 23);

        PanelInput.add(FormInput, java.awt.BorderLayout.CENTER);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.PAGE_START);

        panelGlass6.setName("panelGlass6"); // NOI18N
        panelGlass6.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass6.setLayout(new java.awt.BorderLayout());

        internalFrame2.setBackground(new java.awt.Color(235, 255, 235));
        internalFrame2.setBorder(null);
        internalFrame2.setName("internalFrame2"); // NOI18N
        internalFrame2.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTMLRiwayatPerawatan.setBorder(null);
        LoadHTMLRiwayatPerawatan.setName("LoadHTMLRiwayatPerawatan"); // NOI18N
        Scroll.setViewportView(LoadHTMLRiwayatPerawatan);

        internalFrame2.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass6.add(internalFrame2, java.awt.BorderLayout.CENTER);

        internalFrame1.add(panelGlass6, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,Tgl1,NoRM);}
}//GEN-LAST:event_BtnKeluarKeyPressed

private void NoRMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoRMKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            isPasien();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            isPasien();
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            BtnPasienActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            isPasien();
            
        }
}//GEN-LAST:event_NoRMKeyPressed

private void BtnPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPasienActionPerformed
    if(akses.getpasien()==true){
        DlgCariPasien pasien=new DlgCariPasien(null,true);
        pasien.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
                if(pasien.getTable().getSelectedRow()!= -1){                   
                    NoRM.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(),0).toString());
                    NmPasien.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(),1).toString());
                    Jk.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(),3).toString());
                    TempatLahir.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(),4).toString());
                    TanggalLahir.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(),5).toString());                    
                    Alamat.setText(pasien.getTable().getValueAt(pasien.getTable().getSelectedRow(),7).toString());                    
                }    
                NoRM.requestFocus();
            }
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
        pasien.getTable().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {}
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode()==KeyEvent.VK_SPACE){
                    pasien.dispose();
                }
            }
            @Override
            public void keyReleased(KeyEvent e) {}
        });
        
        pasien.isCek();
        pasien.emptTeks();
        pasien.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
        pasien.setLocationRelativeTo(internalFrame1);
        pasien.setVisible(true);
    }   
}//GEN-LAST:event_BtnPasienActionPerformed

private void BtnPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPasienKeyPressed
    //Valid.pindah(evt,Tgl2,TKd);
}//GEN-LAST:event_BtnPasienKeyPressed

    private void Tgl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tgl1KeyPressed
        Valid.pindah(evt, BtnKeluar, Tgl2);
    }//GEN-LAST:event_Tgl1KeyPressed

    private void Tgl2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tgl2KeyPressed
        Valid.pindah(evt, Tgl1,NoRM);
    }//GEN-LAST:event_Tgl2KeyPressed

    private void BtnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCari1ActionPerformed
        if(NoRM.getText().trim().equals("")||NmPasien.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Pasien masih kosong...!!!");
        }else{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            if (ceksukses == false) {
                ceksukses = true;
                new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        tampilPerawatan();
                        return null;
                    }

                    @Override
                    protected void done() {
                        ceksukses = false;
                    }
                }.execute();
            }
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnCari1ActionPerformed

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        isForm();
    }//GEN-LAST:event_ChkInputActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMRiwayatLaboratorium dialog = new RMRiwayatLaboratorium(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.TextBox Alamat;
    private widget.Button BtnCari1;
    private widget.Button BtnKeluar;
    private widget.Button BtnPasien;
    private widget.CekBox ChkInput;
    private widget.panelisi FormInput;
    private widget.TextBox Jk;
    private widget.editorpane LoadHTMLRiwayatPerawatan;
    private widget.TextBox NmPasien;
    private widget.TextBox NoRM;
    private javax.swing.JPanel PanelInput;
    private widget.TextBox Pekerjaan;
    private widget.RadioButton R1;
    private widget.RadioButton R2;
    private widget.RadioButton R3;
    private widget.ScrollPane Scroll;
    private widget.Tanggal Tanggal;
    private widget.TextBox TanggalLahir;
    private widget.TextBox TempatLahir;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private javax.swing.ButtonGroup buttonGroup1;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.Label label17;
    private widget.Label label18;
    private widget.Label label20;
    private widget.Label label21;
    private widget.Label label22;
    private widget.panelisi panelGlass5;
    private widget.panelisi panelGlass6;
    // End of variables declaration//GEN-END:variables

    public void setNoRm(String norm,String nama) {
        NoRM.setText(norm);
        NmPasien.setText(nama);
        isPasien();
        BtnCari1ActionPerformed(null);
    }
    

    private void isPasien() {
        try{
            ps2=koneksi.prepareStatement(
                    "select pasien.no_rkm_medis,pasien.nm_pasien,pasien.jk,pasien.tmp_lahir,pasien.tgl_lahir,pasien.agama,"+
                    "bahasa_pasien.nama_bahasa,cacat_fisik.nama_cacat,pasien.gol_darah,pasien.nm_ibu,pasien.stts_nikah,pasien.pnd, "+
                    "concat(pasien.alamat,', ',kelurahan.nm_kel,', ',kecamatan.nm_kec,', ',kabupaten.nm_kab) as alamat,pasien.pekerjaan "+
                    "from pasien inner join bahasa_pasien on bahasa_pasien.id=pasien.bahasa_pasien "+
                    "inner join cacat_fisik on cacat_fisik.id=pasien.cacat_fisik "+
                    "inner join kelurahan on pasien.kd_kel=kelurahan.kd_kel "+
                    "inner join kecamatan on pasien.kd_kec=kecamatan.kd_kec "+
                    "inner join kabupaten on pasien.kd_kab=kabupaten.kd_kab "+
                    "where pasien.no_rkm_medis=?");
            try {
                ps2.setString(1,NoRM.getText());
                rs2=ps2.executeQuery();
                if(rs2.next()){
                    NoRM.setText(rs2.getString("no_rkm_medis"));
                    NmPasien.setText(rs2.getString("nm_pasien"));
                    Jk.setText(rs2.getString("jk"));
                    TempatLahir.setText(rs2.getString("tmp_lahir"));
                    TanggalLahir.setText(rs2.getString("tgl_lahir"));
                    Alamat.setText(rs2.getString("alamat"));
                    Pekerjaan.setText(rs2.getString("pekerjaan"));
                }
            } catch (Exception e) {
                System.out.println("Notif : "+e);
            } finally{
                if(rs2!=null){
                    rs2.close();
                }
                if(ps2!=null){
                    ps2.close();
                }
            }
        } catch (Exception e) {
            System.out.println("Notif : "+e);
        }
    }

    private synchronized void tampilPerawatan() {
        try{
            htmlContent = new StringBuilder();
            if(R1.isSelected()==true){
                ps=koneksi.prepareStatement(
                    "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,"+
                    "reg_periksa.kd_dokter,dokter.nm_dokter,poliklinik.nm_poli,reg_periksa.p_jawab,reg_periksa.almt_pj,"+
                    "reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.status_lanjut,penjab.png_jawab,"+
                    "reg_periksa.umurdaftar,reg_periksa.sttsumur "+
                    "from reg_periksa inner join dokter on reg_periksa.kd_dokter=dokter.kd_dokter "+
                    "inner join poliklinik on reg_periksa.kd_poli=poliklinik.kd_poli inner join penjab on reg_periksa.kd_pj=penjab.kd_pj "+
                    "where reg_periksa.stts<>'Batal' and reg_periksa.no_rkm_medis=? order by reg_periksa.tgl_registrasi desc limit 5");
            }else if(R2.isSelected()==true){
                ps=koneksi.prepareStatement(
                    "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,"+
                    "reg_periksa.kd_dokter,dokter.nm_dokter,poliklinik.nm_poli,reg_periksa.p_jawab,reg_periksa.almt_pj,"+
                    "reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.status_lanjut,penjab.png_jawab,"+
                    "reg_periksa.umurdaftar,reg_periksa.sttsumur "+
                    "from reg_periksa inner join dokter on reg_periksa.kd_dokter=dokter.kd_dokter "+
                    "inner join poliklinik on reg_periksa.kd_poli=poliklinik.kd_poli "+
                    "inner join penjab on reg_periksa.kd_pj=penjab.kd_pj "+
                    "where reg_periksa.stts<>'Batal' and reg_periksa.no_rkm_medis=? order by reg_periksa.tgl_registrasi");
            }else if(R3.isSelected()==true){
                ps=koneksi.prepareStatement(
                    "select reg_periksa.no_reg,reg_periksa.no_rawat,reg_periksa.tgl_registrasi,reg_periksa.jam_reg,"+
                    "reg_periksa.kd_dokter,dokter.nm_dokter,poliklinik.nm_poli,reg_periksa.p_jawab,reg_periksa.almt_pj,"+
                    "reg_periksa.hubunganpj,reg_periksa.biaya_reg,reg_periksa.status_lanjut,penjab.png_jawab,"+
                    "reg_periksa.umurdaftar,reg_periksa.sttsumur "+
                    "from reg_periksa inner join dokter on reg_periksa.kd_dokter=dokter.kd_dokter "+
                    "inner join poliklinik on reg_periksa.kd_poli=poliklinik.kd_poli "+
                    "inner join penjab on reg_periksa.kd_pj=penjab.kd_pj "+
                    "where reg_periksa.stts<>'Batal' and reg_periksa.no_rkm_medis=? and "+
                    "reg_periksa.tgl_registrasi between ? and ? order by reg_periksa.tgl_registrasi");
            }
            try{
                i=0;
                if(R1.isSelected()==true){
                    ps.setString(1,NoRM.getText().trim());
                }else if(R2.isSelected()==true){
                    ps.setString(1,NoRM.getText().trim());
                }else if(R3.isSelected()==true){
                    ps.setString(1,NoRM.getText().trim());
                    ps.setString(2,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                    ps.setString(3,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                }            
                urut=0;
                rs=ps.executeQuery();
                while(rs.next()){                                         
                    
                    //menampilkan pemeriksaan radiologi
                    menampikanRiwayatLaboratorium(rs.getString("no_rawat"));
                    
                    
                }//end while utama
                
                LoadHTMLRiwayatPerawatan.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
                htmlContent=null;
            }catch (Exception e) {
                System.out.println("Notifikasi : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            } 
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
    }
    
    private void menampikanRiwayatLaboratorium(String norawat) {
        try {
            urut++;
            htmlContent.append(
                    "<tr class='isi'>").append(
                            "<td valign='top' width='2%'>").append(urut).append("</td>").append(
                    "<td valign='top' width='18%'>No.Rawat</td>").append(
                            "<td valign='top' width='1%' align='center'>:</td>").append(
                            "<td valign='top' width='79%'>").append(rs.getString("no_rawat")).append("</td>").append(
                    "</tr>").append(
                            "<tr class='isi'>").append(
                            "<td valign='top' width='2%'></td>").append(
                            "<td valign='top' width='18%'>Tanggal Registrasi</td>").append(
                            "<td valign='top' width='1%' align='center'>:</td>").append(
                            "<td valign='top' width='79%'>").append(rs.getString("tgl_registrasi")).append(" ").append(rs.getString("jam_reg")).append("</td>").append(
                    "</tr>").append(
                            "<tr class='isi'>").append(
                            "<td valign='top' width='2%'></td>").append(
                            "<td valign='top' width='18%'>Unit/Poliklinik</td>").append(
                            "<td valign='top' width='1%' align='center'>:</td>").append(
                            "<td valign='top' width='79%'>").append(rs.getString("nm_poli")).append(polirujukan).append("</td>").append(
                    "</tr>").append(
                            "<tr class='isi'>").append(
                            "<td valign='top' width='2%'></td>").append(
                            "<td valign='top' width='18%'>Dokter Poli</td>").append(
                            "<td valign='top' width='1%' align='center'>:</td>").append(
                            "<td valign='top' width='79%'>").append(rs.getString("nm_dokter")).append(dokterrujukan).append("</td>").append(
                    "</tr>"
            );
            htmlContent.append(
                    "<tr class='isi'>").append(
                            "<td valign='top' width='2%'></td>").append(
                            "<td valign='top' width='18%'></td>").append(
                            "<td valign='top' width='1%' align='center'>:</td>").append(
                            "<td valign='top' width='79%'>");

            try {
                rs4 = koneksi.prepareStatement(
                        "select periksa_lab.tgl_periksa,periksa_lab.jam from periksa_lab where periksa_lab.kategori<>'PA' and periksa_lab.no_rawat='" + rs.getString("no_rawat") + "' "
                        + "group by concat(periksa_lab.no_rawat,periksa_lab.tgl_periksa,periksa_lab.jam) order by periksa_lab.tgl_periksa,periksa_lab.jam").executeQuery();
                if (rs4.next()) {
                    htmlContent.append(
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>").append(
                                    "<tr><td valign='top' colspan='5'>Pemeriksaan Laboratorium PK & MB</td><td valign='top' colspan='1' align='right'>:</td><td valign='top'></td></tr>").append(
                                    "<tr align='center'>").append(
                                    "<td valign='top' width='4%' bgcolor='#FFFAF8'>No.</td>").append(
                                    "<td valign='top' width='15%' bgcolor='#FFFAF8'>Tanggal</td>").append(
                                    "<td valign='top' width='10%' bgcolor='#FFFAF8'>Kode</td>").append(
                                    "<td valign='top' width='26%' bgcolor='#FFFAF8'>Nama Pemeriksaan</td>").append(
                                    "<td valign='top' width='18%' bgcolor='#FFFAF8'>Dokter PJ</td>").append(
                                    "<td valign='top' width='17%' bgcolor='#FFFAF8'>Petugas</td>").append(
                                    "<td valign='top' width='10%' bgcolor='#FFFAF8'></td>").append(
                                    "</tr>");
                    rs4.beforeFirst();
                    w = 1;
                    while (rs4.next()) {
                        try {
                            rs2 = koneksi.prepareStatement(
                                    "select periksa_lab.kd_jenis_prw, "
                                    + "jns_perawatan_lab.nm_perawatan,petugas.nama,periksa_lab.biaya,periksa_lab.dokter_perujuk,dokter.nm_dokter "
                                    + "from periksa_lab inner join jns_perawatan_lab on periksa_lab.kd_jenis_prw=jns_perawatan_lab.kd_jenis_prw "
                                    + "inner join petugas on periksa_lab.nip=petugas.nip inner join dokter on periksa_lab.kd_dokter=dokter.kd_dokter "
                                    + "where periksa_lab.kategori<>'PA' and periksa_lab.no_rawat='" + rs.getString("no_rawat") + "' "
                                    + "and periksa_lab.tgl_periksa='" + rs4.getString("tgl_periksa") + "' and periksa_lab.jam='" + rs4.getString("jam") + "'").executeQuery();
                            s = 1;
                            while (rs2.next()) {
                                if (s == 1) {
                                    htmlContent.append(
                                            "<tr>").append(
                                                    "<td valign='top' align='center'>").append(w).append("</td>").append(
                                            "<td valign='top'>").append(rs4.getString("tgl_periksa")).append(" ").append(rs4.getString("jam")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("kd_jenis_prw")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("nm_perawatan")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("nm_dokter")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("nama")).append("</td>").append(
                                            "<td valign='top' width='10%' bgcolor='#FFFAF8'></td>").append(
                                            "</tr>"
                                    );
                                } else {
                                    htmlContent.append(
                                            "<tr>").append(
                                                    "<td valign='top' align='center'></td>").append(
                                                    "<td valign='top'></td>").append(
                                                    "<td valign='top'>").append(rs2.getString("kd_jenis_prw")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("nm_perawatan")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("nm_dokter")).append("</td>").append(
                                            "<td valign='top'>").append(rs2.getString("nama")).append("</td>").append(
                                            "<td valign='top' width='10%' bgcolor='#FFFAF8'></td>").append(
                                            "</tr>"
                                    );
                                }

                                biayaperawatan = biayaperawatan + rs2.getDouble("biaya");

                                try {
                                    rs3 = koneksi.prepareStatement(
                                            "select template_laboratorium.Pemeriksaan, detail_periksa_lab.nilai,"
                                            + "template_laboratorium.satuan,detail_periksa_lab.nilai_rujukan,detail_periksa_lab.biaya_item,"
                                            + "detail_periksa_lab.keterangan from detail_periksa_lab inner join "
                                            + "template_laboratorium on detail_periksa_lab.id_template=template_laboratorium.id_template "
                                            + "where detail_periksa_lab.no_rawat='" + rs.getString("no_rawat") + "' and "
                                            + "detail_periksa_lab.kd_jenis_prw='" + rs2.getString("kd_jenis_prw") + "' and "
                                            + "detail_periksa_lab.tgl_periksa='" + rs4.getString("tgl_periksa") + "' and "
                                            + "detail_periksa_lab.jam='" + rs4.getString("jam") + "' order by detail_periksa_lab.kd_jenis_prw,template_laboratorium.urut ").executeQuery();
                                    if (rs3.next()) {
                                        htmlContent.append(
                                                "<tr>").append(
                                                        "<td valign='top' align='center'></td>").append(
                                                        "<td valign='top'></td>").append(
                                                        "<td valign='top'></td>").append(
                                                        "<td valign='top' align='center' bgcolor='#FFFAF8'>Detail Pemeriksaan</td>").append(
                                                        "<td valign='top' align='center' bgcolor='#FFFAF8'>Hasil</td>").append(
                                                        "<td valign='top' align='center' bgcolor='#FFFAF8'>Nilai Rujukan</td>").append(
                                                        "<td valign='top' align='center' bgcolor='#FFFAF8'>Metode</td>").append(
                                                        "</tr>");
                                        do {
                                            switch (rs3.getString("keterangan").toLowerCase()) {
                                                case "l":
                                                    htmlContent.append(
                                                            "<tr>").append(
                                                                    "<td valign='top' align='center'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'>").append(rs3.getString("Pemeriksaan")).append("</td>").append(
                                                            "<td valign='top' style='color:#0000FF'>").append(rs3.getString("nilai").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append(" ").append(rs3.getString("satuan")).append("</td>").append(
                                                            "<td valign='top'>").append(rs3.getString("nilai_rujukan").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append("</td>").append(
                                                            "<td valign='top' align='right'>").append(Valid.SetAngka(rs3.getDouble("biaya_item"))).append("</td>").append(
                                                            "</tr>");
                                                    break;
                                                case "h":
                                                    htmlContent.append(
                                                            "<tr>").append(
                                                                    "<td valign='top' align='center'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'>").append(rs3.getString("Pemeriksaan")).append("</td>").append(
                                                            "<td valign='top' style='color:#FF0000'>").append(rs3.getString("nilai").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append(" ").append(rs3.getString("satuan")).append("</td>").append(
                                                            "<td valign='top'>").append(rs3.getString("nilai_rujukan").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append("</td>").append(
                                                            "<td valign='top' align='right'>").append(Valid.SetAngka(rs3.getDouble("biaya_item"))).append("</td>").append(
                                                            "</tr>");
                                                    break;
                                                case "t":
                                                    htmlContent.append(
                                                            "<tr>").append(
                                                                    "<td valign='top' align='center'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'>").append(rs3.getString("Pemeriksaan")).append("</td>").append(
                                                            "<td valign='top'><b>").append(rs3.getString("nilai").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append(" ").append(rs3.getString("satuan")).append("</b></td>").append(
                                                            "<td valign='top'>").append(rs3.getString("nilai_rujukan").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append("</td>").append(
                                                            "<td valign='top' align='right'>").append(Valid.SetAngka(rs3.getDouble("biaya_item"))).append("</td>").append(
                                                            "</tr>");
                                                    break;
                                                default:
                                                    htmlContent.append(
                                                            "<tr>").append(
                                                                    "<td valign='top' align='center'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'></td>").append(
                                                                    "<td valign='top'>").append(rs3.getString("Pemeriksaan")).append("</td>").append(
                                                            "<td valign='top'>").append(rs3.getString("nilai").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append(" ").append(rs3.getString("satuan").replaceAll("-", "").split("#")[0].trim()).append("</td>").append(
                                                            "<td valign='top'>").append(rs3.getString("nilai_rujukan").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("(\r\n|\r|\n|\n\r)", "<br>")).append("</td>").append(
                                                            "<td valign='top'>").append(rs3.getString("satuan").replaceAll("-", "").split("#")[1].trim()).append("</td>").append(
                                                            "</tr>");
                                            }

                                            biayaperawatan = biayaperawatan + rs3.getDouble("biaya_item");
                                        } while (rs3.next());
                                    }
                                } catch (Exception e) {
                                    System.out.println("Notifikasi : " + e);
                                } finally {
                                    if (rs3 != null) {
                                        rs3.close();
                                    }
                                }
                                s++;
                            }

                            try {
                                rs3 = koneksi.prepareStatement("select saran_kesan_lab.saran,saran_kesan_lab.kesan from saran_kesan_lab where saran_kesan_lab.no_rawat='" + rs.getString("no_rawat") + "' and saran_kesan_lab.tgl_periksa='" + rs4.getString("tgl_periksa") + "' and saran_kesan_lab.jam='" + rs4.getString("jam") + "'").executeQuery();
                                if (rs3.next()) {
                                    htmlContent.append(
                                            "<tr>").append(
                                                    "<td valign='top' align='center'></td>").append(
                                                    "<td valign='top'>Kesan</td>").append(
                                                    "<td valign='top' colspan='5'>: ").append(rs3.getString("kesan")).append("</td>").append(
                                            "</tr>").append(
                                                    "<tr>").append(
                                                    "<td valign='top' align='center'></td>").append(
                                                    "<td valign='top'>Saran</td>").append(
                                                    "<td valign='top' colspan='5'>: ").append(rs3.getString("saran")).append("</td>").append(
                                            "</tr>");
                                }
                            } catch (Exception e) {
                                System.out.println("Notif : " + e);
                            } finally {
                                if (rs3 != null) {
                                    rs3.close();
                                }
                            }
                            w++;
                        } catch (Exception e) {
                            System.out.println("Notifikasi Lab : " + e);
                        } finally {
                            if (rs2 != null) {
                                rs2.close();
                            }
                        }
                    }
                    htmlContent.append(
                            "</table>");
                }
            } catch (Exception e) {
                System.out.println("Notif : " + e);
            } finally {
                if (rs4 != null) {
                    rs4.close();
                }
            }

            try {
                rs2 = koneksi.prepareStatement(
                        "select periksa_lab.tgl_periksa,periksa_lab.jam,periksa_lab.kd_jenis_prw, "
                        + "jns_perawatan_lab.nm_perawatan,petugas.nama,periksa_lab.biaya,periksa_lab.dokter_perujuk,dokter.nm_dokter "
                        + "from periksa_lab inner join jns_perawatan_lab on periksa_lab.kd_jenis_prw=jns_perawatan_lab.kd_jenis_prw "
                        + "inner join petugas on periksa_lab.nip=petugas.nip inner join dokter on periksa_lab.kd_dokter=dokter.kd_dokter "
                        + "where periksa_lab.kategori='PA' and periksa_lab.no_rawat='" + rs.getString("no_rawat") + "' order by periksa_lab.tgl_periksa,periksa_lab.jam").executeQuery();
                if (rs2.next()) {
                    htmlContent.append(
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>").append(
                                    "<tr><td valign='top' colspan='5'>Pemeriksaan Laboratorium PA</td><td valign='top' colspan='1' align='right'>:</td><td valign='top'></td></tr>").append(
                                    "<tr align='center'>").append(
                                    "<td valign='top' width='4%' bgcolor='#FFFAF8'>No.</td>").append(
                                    "<td valign='top' width='15%' bgcolor='#FFFAF8'>Tanggal</td>").append(
                                    "<td valign='top' width='10%' bgcolor='#FFFAF8'>Kode</td>").append(
                                    "<td valign='top' width='26%' bgcolor='#FFFAF8'>Nama Pemeriksaan</td>").append(
                                    "<td valign='top' width='18%' bgcolor='#FFFAF8'>Dokter PJ</td>").append(
                                    "<td valign='top' width='17%' bgcolor='#FFFAF8'>Petugas</td>").append(
                                    "<td valign='top' width='10%' bgcolor='#FFFAF8'></td>").append(
                                    "</tr>");
                    w = 1;
                    do {
                        htmlContent.append(
                                "<tr>").append(
                                        "<td valign='top' align='center'>").append(w).append("</td>").append(
                                "<td valign='top'>").append(rs2.getString("tgl_periksa")).append(" ").append(rs2.getString("jam")).append("</td>").append(
                                "<td valign='top'>").append(rs2.getString("kd_jenis_prw")).append("</td>").append(
                                "<td valign='top'>").append(rs2.getString("nm_perawatan")).append("</td>").append(
                                "<td valign='top'>").append(rs2.getString("nm_dokter")).append("</td>").append(
                                "<td valign='top'>").append(rs2.getString("nama")).append("</td>").append(
                                "<td valign='top' width='10%' bgcolor='#FFFAF8'></td>").append(
                                "</tr>"
                        );
                        biayaperawatan = biayaperawatan + rs2.getDouble("biaya");
                        try {
                            rs3 = koneksi.prepareStatement(
                                    "select detail_periksa_labpa.diagnosa_klinik,detail_periksa_labpa.makroskopik,detail_periksa_labpa.mikroskopik,detail_periksa_labpa.kesimpulan,detail_periksa_labpa.kesan from detail_periksa_labpa "
                                    + "where detail_periksa_labpa.no_rawat='" + rs.getString("no_rawat") + "' and detail_periksa_labpa.kd_jenis_prw='" + rs2.getString("kd_jenis_prw") + "' and "
                                    + "detail_periksa_labpa.tgl_periksa='" + rs2.getString("tgl_periksa") + "' and detail_periksa_labpa.jam='" + rs2.getString("jam") + "'").executeQuery();
                            if (rs3.next()) {
                                file = Sequel.cariIsi("select detail_periksa_labpa_gambar.photo from detail_periksa_labpa_gambar where detail_periksa_labpa_gambar.no_rawat='" + rs.getString("no_rawat") + "' and detail_periksa_labpa_gambar.kd_jenis_prw='" + rs2.getString("kd_jenis_prw") + "' and detail_periksa_labpa_gambar.tgl_periksa='" + rs2.getString("tgl_periksa") + "' and detail_periksa_labpa_gambar.jam='" + rs2.getString("jam") + "'");
                                htmlContent.append(
                                        "<tr>").append(
                                                "<td valign='top' align='center'></td>").append(
                                                "<td valign='top'></td>").append(
                                                "<td valign='top'>Diagnosa Klinis</td>").append(
                                                "<td valign='top' colspan='4'>: ").append(rs3.getString("diagnosa_klinik")).append("</td>").append(
                                        "</tr>").append(
                                                "<tr>").append(
                                                "<td valign='top' align='center'></td>").append(
                                                "<td valign='top'></td>").append(
                                                "<td valign='top'>Makroskopik</td>").append(
                                                "<td valign='top' colspan='4'>: ").append(rs3.getString("makroskopik")).append("</td>").append(
                                        "</tr>").append(
                                                "<tr>").append(
                                                "<td valign='top' align='center'></td>").append(
                                                "<td valign='top'></td>").append(
                                                "<td valign='top'>Mikroskopik</td>").append(
                                                "<td valign='top' colspan='4'>: ").append(rs3.getString("mikroskopik")).append("</td>").append(
                                        "</tr>").append(
                                                "<tr>").append(
                                                "<td valign='top' align='center'></td>").append(
                                                "<td valign='top'></td>").append(
                                                "<td valign='top'>Kesimpulan</td>").append(
                                                "<td valign='top' colspan='4'>: ").append(rs3.getString("kesimpulan")).append("</td>").append(
                                        "</tr>").append(
                                                "<tr>").append(
                                                "<td valign='top' align='center'></td>").append(
                                                "<td valign='top'></td>").append(
                                                "<td valign='top'>Kesan</td>").append(
                                                "<td valign='top' colspan='4'>: ").append(rs3.getString("kesan")).append("</td>").append(
                                        "</tr>"
                                );
                                if (!file.equals("")) {
                                    htmlContent.append(
                                            "<tr>").append(
                                                    "<td valign='top' align='center'></td>").append(
                                                    "<td valign='top'></td>").append(
                                                    "<td valign='top' colspan='5' align='center'><a href='http://").append(koneksiDB.HOSTHYBRIDWEB()).append(":").append(koneksiDB.PORTWEB()).append("/").append(koneksiDB.HYBRIDWEB()).append("/labpa/").append(file).append("'><img alt='Gambar PA' src='http://").append(koneksiDB.HOSTHYBRIDWEB()).append(":").append(koneksiDB.PORTWEB()).append("/").append(koneksiDB.HYBRIDWEB()).append("/labpa/").append(file).append("' width='450' height='450'/></a></td>").append(
                                            "</tr>"
                                    );
                                }
                            }
                        } catch (Exception e) {
                            System.out.println("Notifikasi : " + e);
                        } finally {
                            if (rs3 != null) {
                                rs3.close();
                            }
                        }
                        w++;
                    } while (rs2.next());

                    htmlContent.append(
                            "</table>");
                }
            } catch (Exception e) {
                System.out.println("Notifikasi Lab : " + e);
            } finally {
                if (rs2 != null) {
                    rs2.close();
                }
            }

            htmlContent.append(
                    "</td>").append(
                            "</tr>");
        } catch (Exception e) {
            System.out.println("Notifikasi Lab : " + e);
        }
    }
    
    private String getUrlRadiologi(String lokasi) {
        return "http://" + koneksiDB.HOSTHYBRIDWEB() + ":" + koneksiDB.PORTWEB()
                + "/" + koneksiDB.HYBRIDWEB() + "/radiologi/" + lokasi;
    }
    
    private void isForm(){
        if(ChkInput.isSelected()==true){
            ChkInput.setVisible(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH,80));
            FormInput.setVisible(true);      
            ChkInput.setVisible(true);
        }else if(ChkInput.isSelected()==false){           
            ChkInput.setVisible(false);            
            PanelInput.setPreferredSize(new Dimension(WIDTH,20));
            FormInput.setVisible(false);      
            ChkInput.setVisible(true);
        }
    }
    

}
