/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author perpustakaan
 */
public class DlgCatatan extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public DlgCatatan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        
        //TCatatan.setText(TCatatan); 
        TCatatan.setLineWrap(true);
        TCatatan.setWrapStyleWord(true);
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        jLabel3 = new widget.Label();
        BtnHapusCatatanReg = new widget.Button();
        TNoRM = new widget.TextBox();
        TPasien = new widget.TextBox();
        jLabel9 = new widget.Label();
        Scroll3 = new widget.ScrollPane();
        TCatatan = new widget.TextArea();
        TNoRawat = new widget.TextBox();
        jLabel10 = new widget.Label();
        Scroll4 = new widget.ScrollPane();
        TCatatanReg = new widget.TextArea();
        BtnHapusCatatanPasien = new widget.Button();
        panelGlass8 = new widget.panelisi();
        BtnSimpan = new widget.Button();
        BtnHapus = new widget.Button();
        BtnEdit = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Catatan Untuk Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput.setLayout(null);

        jLabel3.setText("No.R.M. :");
        jLabel3.setName("jLabel3"); // NOI18N
        FormInput.add(jLabel3);
        jLabel3.setBounds(0, 10, 65, 23);

        BtnHapusCatatanReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cancel.png"))); // NOI18N
        BtnHapusCatatanReg.setMnemonic('H');
        BtnHapusCatatanReg.setToolTipText("Alt+H");
        BtnHapusCatatanReg.setName("BtnHapusCatatanReg"); // NOI18N
        BtnHapusCatatanReg.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapusCatatanReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusCatatanRegActionPerformed(evt);
            }
        });
        BtnHapusCatatanReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusCatatanRegKeyPressed(evt);
            }
        });
        FormInput.add(BtnHapusCatatanReg);
        BtnHapusCatatanReg.setBounds(70, 170, 30, 30);
        BtnHapus.setVisible(false);

        TNoRM.setEditable(false);
        TNoRM.setHighlighter(null);
        TNoRM.setName("TNoRM"); // NOI18N
        FormInput.add(TNoRM);
        TNoRM.setBounds(70, 10, 90, 23);

        TPasien.setEditable(false);
        TPasien.setHighlighter(null);
        TPasien.setName("TPasien"); // NOI18N
        TPasien.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(TPasien);
        TPasien.setBounds(288, 10, 400, 23);

        jLabel9.setText("Catatan Pasien:");
        jLabel9.setName("jLabel9"); // NOI18N
        FormInput.add(jLabel9);
        jLabel9.setBounds(0, 40, 100, 23);

        Scroll3.setName("Scroll3"); // NOI18N
        Scroll3.setOpaque(true);

        TCatatan.setColumns(20);
        TCatatan.setRows(5);
        TCatatan.setName("TCatatan"); // NOI18N
        Scroll3.setViewportView(TCatatan);

        FormInput.add(Scroll3);
        Scroll3.setBounds(110, 40, 580, 100);

        TNoRawat.setEditable(false);
        TNoRawat.setHighlighter(null);
        TNoRawat.setName("TNoRawat"); // NOI18N
        TNoRawat.setPreferredSize(new java.awt.Dimension(25, 28));
        FormInput.add(TNoRawat);
        TNoRawat.setBounds(165, 10, 120, 23);

        jLabel10.setText("Catatan Registrasi:");
        jLabel10.setName("jLabel10"); // NOI18N
        FormInput.add(jLabel10);
        jLabel10.setBounds(0, 150, 100, 23);

        Scroll4.setName("Scroll4"); // NOI18N
        Scroll4.setOpaque(true);

        TCatatanReg.setColumns(20);
        TCatatanReg.setRows(5);
        TCatatanReg.setName("TCatatanReg"); // NOI18N
        Scroll4.setViewportView(TCatatanReg);

        FormInput.add(Scroll4);
        Scroll4.setBounds(110, 150, 580, 100);

        BtnHapusCatatanPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cancel.png"))); // NOI18N
        BtnHapusCatatanPasien.setMnemonic('H');
        BtnHapusCatatanPasien.setToolTipText("Alt+H");
        BtnHapusCatatanPasien.setName("BtnHapusCatatanPasien"); // NOI18N
        BtnHapusCatatanPasien.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapusCatatanPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusCatatanPasienActionPerformed(evt);
            }
        });
        BtnHapusCatatanPasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusCatatanPasienKeyPressed(evt);
            }
        });
        FormInput.add(BtnHapusCatatanPasien);
        BtnHapusCatatanPasien.setBounds(70, 60, 30, 30);
        BtnHapus.setVisible(false);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(100, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpan.setMnemonic('S');
        BtnSimpan.setText("Simpan");
        BtnSimpan.setToolTipText("Alt+S");
        BtnSimpan.setName("BtnSimpan"); // NOI18N
        BtnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        BtnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnSimpanKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnSimpan);

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/stop_f2.png"))); // NOI18N
        BtnHapus.setMnemonic('H');
        BtnHapus.setText("Hapus");
        BtnHapus.setToolTipText("Alt+H");
        BtnHapus.setName("BtnHapus"); // NOI18N
        BtnHapus.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        BtnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnHapusKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnHapus);
        //BtnHapus.setVisible(false);

        BtnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/inventaris.png"))); // NOI18N
        BtnEdit.setMnemonic('G');
        BtnEdit.setText("Ganti");
        BtnEdit.setToolTipText("Alt+G");
        BtnEdit.setName("BtnEdit"); // NOI18N
        BtnEdit.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });
        BtnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnEdit);
        BtnEdit.setVisible(false);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Tutup");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        if(TNoRM.getText().trim().equals("")||TPasien.getText().trim().equals("")){
            Valid.textKosong(TNoRM,"No.Rekam Medis");
        }else{  
            if(!TCatatan.getText().trim().equals("")){
                Sequel.menyimpan3("catatan_pasien","?,?",2,new String[]{TNoRM.getText(),TCatatan.getText()},"no_rkm_medis=?","catatan=?",2,new String[]{TCatatan.getText(),TNoRM.getText()});
            }
            
            if(Sequel.cariInteger("SELECT count(no_rawat) from catatan_registrasi where no_rawat=? and status = '1'", TNoRawat.getText()) > 0){
                Sequel.mengedit("catatan_registrasi", "no_rawat='"+TNoRawat.getText()+"' and status='1'", "catatan='"+TCatatanReg.getText()+"',updated_at=now()");
            }else{
                Sequel.menyimpan2("catatan_registrasi","?,?,'1', now(), now()", 2,new String[]{TNoRawat.getText(),TCatatanReg.getText()});
            }
            
//            if(!TCatatanReg.getText().trim().equals("") && !TNoRawat.getText().trim().equals("")){
//                 Sequel.menyimpan3("catatan_registrasi","?,?,'1', now(), now()",2,new String[]{TNoRawat.getText(),TCatatanReg.getText()},"no_rawat=? and status='1'","catatan=?,updated_at=now()",2,new String[]{TCatatanReg.getText(),TNoRawat.getText()});
//            }
//            BtnKeluarActionPerformed(evt);     
            tampilCatatan();
        }  
}//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnSimpanKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnSimpanActionPerformed(null);
        }else{
            Valid.pindah(evt,TCatatan,BtnKeluar);
        }
}//GEN-LAST:event_BtnSimpanKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
       Sequel.meghapus2("catatan_pasien","no_rkm_medis",TNoRM.getText());
       Sequel.mengedit("catatan_registrasi","no_rawat='"+TNoRawat.getText()+"' and status='1'","status='0', updated_at=now()");
       TCatatan.setText("");
       TCatatanReg.setText("");
       BtnKeluarActionPerformed(evt);       
}//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusKeyPressed
        
}//GEN-LAST:event_BtnHapusKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
    if(TNoRM.getText().trim().equals("")||TPasien.getText().trim().equals("")){
        Valid.textKosong(TNoRM,"No.Rekam Medis");
    }else{  
        if(TCatatan.getText().trim().equals("")){
           Sequel.meghapus("catatan_pasien","no_rkm_medis",TNoRM.getText());
        }else{
             Sequel.mengedit("catatan_pasien","no_rkm_medis='"+TNoRM.getText()+"'","catatan='"+TCatatan.getText()+"'");
        }
        
        if(TCatatanReg.getText().trim().equals("")){
           Sequel.mengedit("catatan_registrasi","no_rawat='"+TNoRawat.getText()+"' and status='1'","status='0', updated_at=now()");
        }else{
            Sequel.mengedit2("catatan_registrasi","no_rawat=? and status='1'","catatan=?, updated_at=now()",2,new String[]{
                TCatatanReg.getText(),TNoRawat.getText()
            });
        }
        BtnKeluarActionPerformed(evt);
    }
}//GEN-LAST:event_BtnEditActionPerformed

private void BtnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnEditActionPerformed(null);
        }
}//GEN-LAST:event_BtnEditKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TCatatan.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void BtnHapusCatatanRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusCatatanRegActionPerformed
//       Sequel.mengedit("catatan_registrasi","no_rawat='"+TNoRawat.getText()+"' and status='1'","status='0', updated_at=now()");
       
        Sequel.mengedit2("catatan_registrasi", "no_rawat=? and status='1'", "status='0', updated_at=now()", 1, new String[]{
            TNoRawat.getText()
        });
        
       TCatatanReg.setText("");
    }//GEN-LAST:event_BtnHapusCatatanRegActionPerformed

    private void BtnHapusCatatanRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusCatatanRegKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHapusCatatanRegKeyPressed

    private void BtnHapusCatatanPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusCatatanPasienActionPerformed
       Sequel.meghapus2("catatan_pasien","no_rkm_medis",TNoRM.getText());
       TCatatan.setText("");
    }//GEN-LAST:event_BtnHapusCatatanPasienActionPerformed

    private void BtnHapusCatatanPasienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnHapusCatatanPasienKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHapusCatatanPasienKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCatatan dialog = new DlgCatatan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnEdit;
    private widget.Button BtnHapus;
    private widget.Button BtnHapusCatatanPasien;
    private widget.Button BtnHapusCatatanReg;
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpan;
    private widget.PanelBiasa FormInput;
    private widget.ScrollPane Scroll3;
    private widget.ScrollPane Scroll4;
    private widget.TextArea TCatatan;
    private widget.TextArea TCatatanReg;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRawat;
    private widget.TextBox TPasien;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel3;
    private widget.Label jLabel9;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TPasien,TNoRM.getText());
    }

    public void setNoRm(String norm, String no_rawat) {
        TNoRM.setText(norm);
        TNoRawat.setText(no_rawat);
        isPsien();

//        Sequel.cariIsi(
//                "select catatan_pasien.catatan from catatan_pasien where catatan_pasien.no_rkm_medis=?",
//                TCatatan,
//                TNoRM.getText()
//        );
        TCatatanReg.setEditable(true);
        
        if(TNoRawat.getText().trim().equals("")){
            TCatatanReg.setEditable(false);
        }else{
           TCatatanReg.setEditable(true);
//           Sequel.cariIsi("select catatan_registrasi.catatan from catatan_registrasi where catatan_registrasi.no_rawat=? and catatan_registrasi.status = '1' ",TCatatanReg,TNoRawat.getText());       
        }
        
        tampilCatatan();
    }
    
    public void tampilCatatan(){
         Sequel.cariIsi(
                "select catatan_pasien.catatan from catatan_pasien where catatan_pasien.no_rkm_medis=?",
                TCatatan,
                TNoRM.getText()
        );
         
        Sequel.cariIsi("select catatan_registrasi.catatan from catatan_registrasi where catatan_registrasi.no_rawat=? and catatan_registrasi.status = '1' ",TCatatanReg,TNoRawat.getText());       
    }

// Overload (tanpa no_rawat)
    public void setNoRm(String norm) {
        setNoRm(norm, "");
    }
    
    public void isCek(){
        BtnSimpan.setEnabled(true);
        BtnHapus.setEnabled(true);
        BtnEdit.setEnabled(true);        
    }



}
